server:
  port: 8080
  servlet:
    context-path: /demo
qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey: JWV3m7mE3Uj5oNXm3C27BEaPNfTf8oYJx-QEG5Xx
  ## 此处填写你自己的七牛云 secret key
  secretKey: m4QW4WBmzMHDz_hgGmQPhxdklulWv4wUk8cNyvLc
  ## 此处填写你自己的七牛云 bucket
  bucket: hutu-public
  ## 此处填写你自己的七牛云 域名
  prefix: hutu
spring:
  servlet:
    multipart:
      enabled: true
      location: D:\data\apps\temp
      file-size-threshold: 5MB
      max-file-size: 20MB
